#!/usr/bin/env python

###! /usr/bin/python

import os 


flag_empty = (os.stat('scratch/solver/000002/solver.log').st_size ==0)
#flag_empty = (os.stat('scratch/solver/000000/first_specfem_run.log').st_size ==0)

print flag_empty 
