#!/bin/bash

## copy all my code to my_all then update github 
rm -rf my_* 
cp -rf ../my_* . 

wait

git add .
git commit -m "16th commit: Matlab for istf"
#git push -u github master
git push origin master

