#!/bin/sh

echo "copy all files to current folder from jiazeh@paris:/home/jiazeh/temp"

#firefox "https://www.google.com/"

#cd /home/jiazeh/Desktop/my_files/my_bin

scp -r jiazeh@paris:/home/jiazeh/temp/* . 
