#!/bin/bash

### quickly clean the backup slurmtop folders

# created on Wed Nov 21 16:57:42 EST 2018
# created by Jiaze He 


##rm -r [c]* & 
#rm -r [d]*  

#rm -r [0]* & 
#rm -r [1]* & 
#rm -r [2]* & 
#rm -r [3]* & 
#rm -r [4]* & 
#rm -r [5]* & 
#rm -r [6]* & 
#rm -r [7]* & 
#rm -r [8]* & 
#rm -r [9]* & 
#rm -r [a]* & 
#rm -r [b]* & 
#rm -r [c]* & 
#rm -r [d]* & 
#rm -r [e]* & 
#rm -r [f]*  
rm -r [01234]* & 
rm -r [56789]* & 
rm -r [abcdef]*  

echo 'cleaning up finished'





