#!/usr/bin/env python

#import os
#print("The python script has been invoked successfully")
#print(os.environ['flag_seismotype'])

import numpy as np
import matplotlib.pyplot as plt

###from myFormat.ze_plot_summary import one_signal_plot,txt_signal_load

#one_signal_plot(t,nd_a[1,:],figtitle='hey',y_label='foo')

##stf_load = txt_signal_load()
##one_signal_plot(stf_load[:,0],stf_load[:,1])
#one_signal_plot(stf_load[:,0],stf_load[:,1],figtitle='hey',y_label='foo')

#stf_load = np.loadtxt("DATA/stf_tbd_csic3")
#stf_load = np.loadtxt("/home/jiazeh/Desktop/my_files/py2project/pythonvenv_playground/james_source_inversion/obf/output/stf_ricker_delayed")
stf_load = np.loadtxt("specfem_data/stf_3pks_small_delayed300k_bk")
#print('stf_load shape',stf_load.shape)

plt.plot(stf_load[:,0],stf_load[:,1])
plt.show()




