#!/bin/bash

#./printgllmap ./scratch/evalgrad/gradient_nomask/ last
#./Printgllmap ./scratch/evalgrad/model last
./printgllmap ./scratch/evalgrad/gradient last
#./printgllmap ./scratch/evalgrad/kernels/000000/ last
#./printgllmap ./scratch/evalgrad/kernels/sum/ last

