#!/bin/sh
''''exec python -W ignore -- "$0" "$@" # '''

# created on Sat Nov 24 17:43:30 EST 2018 
# created by Jiaze, based on EB's code 

# revised on Fri Dec  7 12:26:13 EST 2018 
# ylab.title(par + ' iter num' +K, size=26)

execfile('zplotgll_libload.py')

if __name__ == '__main__':
    """ Plots data on 2-D unstructured mesh

    Reads mesh coordinates from first two columns of text file and data from
    subsequent columns, computes Delaunay triangulation, and plots data
    using matplotlib.

    In particular, can be used to plot kernels and models output from SPECFEM2D
    on unstructured GLL bases.
    """
    xz_dirname = sys.argv[1]
    dirname = sys.argv[2]
    K = sys.argv[3]
    #x = sys.argv[4]
    #y = sys.argv[5]
    par = sys.argv[4]

    execfile('zplotgll_common_parts.py')
    pylab.title(par + ' iter num' +K, size=26)
    plt.savefig( 'output/' + par + '_' + K +'.png')
