#!/bin/sh

echo "copy all files in current folder to jiazeh@paris:/home/jiazeh/Dropbox (Princeton)/Sync/princeton/quick_transfer"

eval scp -r $1 "jiazeh@paris:/home/jiazeh/Dropbox\ \(Princeton\)/Sync/princeton/quick_transfer"
#scp -r ./* jiazeh@paris:/home/jiazeh/temp
