#!/usr/bin/env python

# Specialized script used to visualize seismic section.

import argparse

from obspy import read
import matplotlib.pyplot as plt

from seisflows.tools.graphics import plot_vector, plot_section

import numpy as np

# added on Fri May 24 11:48:04 EDT 2019
from my_sfs.ze_seisflows import parse_args 

if __name__ == "__main__":

    args = parse_args()

    if args.clip < 0:
        args.clip = 0
    elif args.clip > 100:
        args.clip = 100

    stream = read(args.file, format='SU', byteorder='<')
    plot_section(stream,
                 cmap=args.cmap,
                 clip=(100-args.clip),
                 title=args.title,
                 x_interval=args.x_interval,
                 y_interval=args.y_interval)
    #plt.show()
    plt.savefig(args.save)



